apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-server
  template:
    metadata:
      name: app-server
      labels: 
        app: app-server
    spec:
      containers:
        - name: app-server
          image: yaksininavab/my-flask-app:latest
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: app-server-service
  labels: 
    app: app-server
spec:
  type: LoadBalancer
  selector:
    app: app-server
  ports:
    - port: 5000