name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Check kubeconfig
      run: |
        kubectl config view
        kubectl cluster-info

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.9.0'  # Specify the desired Helm version
      id: install

    - name: Add helm repo
      run: |
        helm repo add public-ip-repo https://yaksin-inavab.github.io/public_ip_app_helm_chart/charts/public-ip-app-helmchart/


    - name: Check Helm status
      run: |
        helm version
        helm repo list

    #- name: Package helm 
    #  run: |
    #    helm package my-flask-app 


    - name: Deploy to EKS
      run: |
        helm upgrade --install my-flask-app ./my-flask-app-0.1.0.tgz
