name: CI Workflow

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest test_app.py

    - name: Build Docker image
      run: |
        docker build -t my-flask-app .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker tag my-flask-app yaksininavab/my-flask-app:latest
        docker push yaksininavab/my-flask-app:latest

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.9.0'  # Specify the desired Helm version

    - name: Configure Kubernetes Access
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG

    - name: Add Helm repository
      run: |
        helm repo add my-github-repo https://yaksin-inavab.github.io/public_ip_app_helm_chart/
        helm repo update

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install my-flask-app my-github-repo/my-flask-app --namespace default --create-namespace
