name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests  # Adjust if your test directory is different

    - name: Build Docker image
      run: |
        docker build -t my-flask-app .  # Adjust Docker image name as needed

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker tag my-flask-app my-dockerhub-username/my-flask-app:latest
        docker push my-dockerhub-username/my-flask-app:latest  # Push the Docker image to Docker Hub
